# Generated by Django 4.1.2 on 2022-11-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
